export const GET_USER_INFO = "GET_USER_INFO";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const FETCH_QUESTIONS_START = "FETCH_QUESTIONS_START";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_FAIL = "FETCH_QUESTIONS_FAIL";
export const FETCH_TOTAL_QUESTION_COUNT_START = "FETCH_TOTAL_QUESTION_COUNT_START";
export const FETCH_TOTAL_QUESTION_COUNT_SUCCESS ="FETCH_TOTAL_QUESTION_COUNT_SUCCESS";
export const FETCH_TOTAL_QUESTION_COUNT_FAIL = "FETCH_TOTAL_QUESTION_COUNT_FAIL";

export const FETCH_SELECTED_QUESTION_START = "FETCH_SELECTED_QUESTION_START";
export const FETCH_SELECTED_QUESTION_SUCCESS = "FETCH_SELECTED_QUESTION_SUCCESS";
export const FETCH_SELECTED_QUESTION_FAIL = "FETCH_SELECTED_QUESTION_FAIL";
export const FETCH_ANSWERS_START = "FETCH_ANSWERS_START";
export const FETCH_ANSWERS_SUCCESS = "FETCH_ANSWERS_SUCCESS";
export const FETCH_ANSWERS_FAIL = "FETCH_ANSWERS_FAIL";
export const ADD_ANSWER = "ADD_ANSWER";
export const SEND_ANSWER_START = "SEND_ANSWER_START";
export const SEND_ANSWER_SUCCESS = "SEND_ANSWER_SUCCESS";
export const SEND_ANSWER_FAIL = "SEND_ANSWER_FAIL";
export const IS_SOLVED_QUESTION = "IS_SOLVED_QUESTION";
