export const GET_USER_INFO = "GET_USER_INFO";

// FOR AUTHENTICATION
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

// FOR HOME PAGE
export const FETCH_TOTAL_QUESTION_COUNT_START =
  "FETCH_TOTAL_QUESTION_COUNT_START";
export const FETCH_TOTAL_QUESTION_COUNT_SUCCESS =
  "FETCH_TOTAL_QUESTION_COUNT_SUCCESS";
export const FETCH_TOTAL_QUESTION_COUNT_FAIL =
  "FETCH_TOTAL_QUESTION_COUNT_FAIL";

export const FETCH_QUESTIONS_START = "FETCH_QUESTIONS_START";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_FAIL = "FETCH_QUESTIONS_FAIL";

export const FETCH_UNSOLVED_QUESTION_COUNT_START =
  "FETCH_UNSOLVED_QUESTION_COUNT_START";
export const FETCH_UNSOLVED_QUESTION_COUNT_SUCCESS =
  "FETCH_UNSOLVED_QUESTION_COUNT_SUCCESS";
export const FETCH_UNSOLVED_QUESTION_COUNT_FAIL =
  "FETCH_UNSOLVED_QUESTION_COUNT_FAIL";

export const FETCH_SOLVED_QUESTION_COUNT_START =
  "FETCH_SOLVED_QUESTION_COUNT_START";
export const FETCH_SOLVED_QUESTION_COUNT_SUCCESS =
  "FETCH_SOLVED_QUESTION_COUNT_SUCCESS";
export const FETCH_SOLVED_QUESTION_COUNT_FAIL =
  "FETCH_SOLVED_QUESTION_COUNT_FAIL";

// FOR ANSWERS PAGE
export const FETCH_QUESTION_START = "FETCH_QUESTION_START";
export const FETCH_QUESTION_SUCCESS = "FETCH_QUESTION_SUCCESS";
export const FETCH_QUESTION_FAIL = "FETCH_QUESTION_FAIL";

export const FETCH_ANSWERS_START = "FETCH_ANSWERS_START";
export const FETCH_ANSWERS_SUCCESS = "FETCH_ANSWERS_SUCCESS";
export const FETCH_ANSWERS_FAIL = "FETCH_ANSWERS_FAIL";

// FOR NEW ANSWER
export const SET_NEW_ANSWER_CONTENT = "SET_NEW_ANSWER_CONTENT";
export const SET_NEW_ANSWER_USERNAME = "SET_NEW_ANSWER_USERNAME";
export const SET_NEW_ANSWER_EMAIL = "SET_NEW_ANSWER_EMAIL";
export const SET_NEW_ANSWER_IMAGE_AS_FILE = "SET_NEW_ANSWER_IMAGE_AS_FILE";

export const POST_ANSWER_START = "POST_ANSWER_START";
export const POST_ANSWER_SUCCESS = "POST_ANSWER_SUCCESS";
export const POST_ANSWER_FAIL = "POST_ANSWER_START";

export const UPDATE_QUESTION_REPLY_COUNT = "UPDATE_QUESTION_REPLY_COUNT";
export const UPDATE_UNSOLVED_QUESTION_COUNT = "UPDATE_UNSOLVED_QUESTION_COUNT";
export const POST_IMAGE_TO_FIREBASE = "POST_IMAGE_TO_FIREBASE";

// FOR NEW QUESTION
export const SET_NEW_QUESTION_USERNAME = "SET_NEW_QUESTION_USERNAME";
export const SET_NEW_QUESTION_EMAIL = "SET_NEW_QUESTION_EMAIL";
export const SET_NEW_QUESTION_CONTENT = "SET_NEW_QUESTION_CONTENT";
export const SET_NEW_QUESTION_TITLE = "SET_NEW_QUESTION_TITLE";
export const SET_NEW_QUESTION_HELPER_URL = "SET_NEW_QUESTION_HELPER_URL";
export const SET_NEW_QUESTION_IMAGE_AS_FILE = "SET_NEW_QUESTION_IMAGE_AS_FILE";

export const POST_NEW_QUESTION_START = "POST_NEW_QUESTION_START";
export const POST_NEW_QUESTION_SUCCESS = "POST_NEW_QUESTION_SUCCESS";
export const POST_NEW_QUESTION_FAIL = "POST_NEW_QUESTION_FAIL";

export const SET_NEW_QUESTION_IS_EDIT = "SET_NEW_QUESTION_IS_EDIT";
